### ISSUE TITLE
Failed-Network Error while downloading larger data

### ISSUE THREAD

**Issue by suprajareddy11** [abdennour/react-csv#62] opened 2018-02-04 19:53 UTC
In the data property, am setting up array of big data size of around 16995 items. Where each array item is having around 16 properties/attributes. I am setting the component as shown below:
<CSVLink
                      data={this.state.myData}
                      filename="download.csv"
                      className="text-white"
                      style={{'textDecoration': 'none'}}
                      target="_blank" />

here this.state.myData is having 16995 items and each item is holding around 16 properties.

Kindly suggest!

**Comment by mriccid** [comment] 2018-02-08 23:07
This looks like a duplicate of https://github.com/abdennour/react-csv/issues/44

**Closed** 2018-03-07 22:53 UTC

**Comment by mriccid** [comment] 2018-03-07 23:08
react-csv@1.0.14 fixes this issue 👍
