### ISSUE TITLE
IE Object.assign issue

### ISSUE THREAD

**Issue by waifo** [abdennour/react-csv#19] opened 2017-04-20 14:55 UTC
You are not using any polyfill for Object.assign so this library is not working in IE

**Comment by abdennour** [comment] 2017-04-23 08:15
Duplicate of #9

**Comment by M00staff** [comment] 2017-06-29 21:03
So I'm also having trouble getting this to work on ie11.  I've been playing with the object.assign polyfill but still can't get it working.  

Is there something I'm missing?

**Comment by abdennour** [comment] 2017-07-02 08:53
أهلا مصطفى ، هل بإمكانك أن تضيف هذا الكود 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by M00staff** [comment] 2017-07-07 13:50
Yea, i added that code snippet into the library and it still wasn't working.  

Was i putting it into the wrong place?

Thanks!

**Comment by Michael-Brooks** [comment] 2017-07-19 13:51
Rather than trying to point us to a fix and get us to implement it ourselves, shouldn't you or another contributor be fixing the issue?

Using the sample given, I opened it up in Chrome and the sample-site page displayed correctly and I could download the file. When viewing in IE11, it wouldn't show the sample page. I added the polyfill you linked to and now the page is displaying, but the download button still doesn't work.

I'm trying to find a fix for the issue myself, but the console doesn't log any errors and I don't know anything about the library at all. It would be great if you could actually debug and create a fix rather than throwing links around.

**Comment by Michael-Brooks** [comment] 2017-07-20 08:43
The reason for the download not working is because it's either using the wrong functions, or because the URI isn't correct for IE. I have done a little Googling and have found that this could be the solution https://stackoverflow.com/questions/18185660/javascript-jquery-exporting-data-in-csv-not-working-in-ie

I'm now just trying to work out how we can add this in to library. If anyone has any suggestions, then please feel free to help me out.

**Comment by minotaurrr** [comment] 2017-10-19 03:17
any progress on this?

**Comment by mriccid** [comment] 2018-01-23 11:21
Thanks for your input. This is a duplicate of #25 which has been fixed.

**Closed by mriccid** 2018-01-23 11:21 UTC
